# Generated by Django 2.2.4 on 2019-09-05 13:52

from django.db import migrations, models
import django.db.models.deletion
from cie.cie10 import CIECodes


def import_data(apps, schema_editor):
    CIE10Code = apps.get_model('cie', 'CIE10Code')
    manager = CIECodes()
    for code, content in manager.tree.items():
        full_info = manager.info(code=code).copy()    
        full_info['multiple_descriptions'] = '\n'.join(full_info['multiple_descriptions'])
        if full_info.get('depends_on'):
            full_info['depends_on'] = CIE10Code.objects.get(code=full_info['depends_on'])
        instance = CIE10Code.objects.create(**full_info)    
        print(f'Importado {instance.code}: {instance.description}')




class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIE10Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('multiple_descriptions', models.TextField()),
                ('depends_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cie.CIE10Code')),
            ],
        ),
        migrations.RunPython(import_data, lambda a, s: None)
    ]
